services:
    postgres:
        image: 'postgres:17-alpine'
        environment:
            - 'POSTGRES_DB=postgres'
            - 'POSTGRES_PASSWORD=postgres'
            - 'POSTGRES_USER=postgres'
        ports:
            - '15432:5432'