services:
    postgres:
        image: 'postgres:17-alpine'
        environment:
            - 'POSTGRES_DB=postgres'
            - 'POSTGRES_PASSWORD=postgres'
            - 'POSTGRES_USER=postgres'
        ports:
            - '5432'

    spring-boot-url-shortener:
        image: mnibras/url-shortener
        container_name: url-shortener
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
        ports:
            - "8080:8080"
        restart: unless-stopped
        depends_on:
            - postgres